### ISSUE TITLE
Adding boost to default libraries

### ISSUE THREAD

**Issue by mcc-devel** [zero9178/GNU-Toolchain-for-Windows#2]
Boost is a very powerful librery for C++, so consider adding it to the default libraries.
You can download it from [here](https://sourceforge.net/projects/boost/files/boost/$version).
PS: $version is the version you want, preferably latest stable for gcc7-10; latest beta for gcc trunk.

**Comment by zero9178** [comment]
I'd rather prefer this repo to be the most barebone toolchain possible. So it shall only include all the things needed for all the features that the GNU project make available through GCC and binutils. That way other people could build on top of it and there aren't any issues distinguishing which files are vital to the toolchain or what files are part of a library such as boost etc. Compiling boost oneself should not be a problem I believe

**Comment by mcc-devel** [comment]
As you prefer, please.
