### ISSUE TITLE
ld problem

### ISSUE THREAD

**Issue by mcc-devel** [zero9178/GNU-Toolchain-for-Windows#4]
https://user-images.githubusercontent.com/74864408/104147096-f9f4b400-5407-11eb-8582-b0927d9c4e66.mp4

I met this ld problem, see video for more info.

**Comment by zero9178** [comment]
I have pushed a commit that I think should fix this. Probably stripped too much when trying to cut debug info

**Comment by mcc-devel** [comment]
it works now.
