### ISSUE TITLE
gcc start c++23 cupport

### ISSUE THREAD

**Issue by mcc-devel** [zero9178/GNU-Toolchain-for-Windows#5]
g++ now supports c++23, so maybe we should update the binaries ASAP

**Comment by zero9178** [comment]
Only the very first proposals have been accepted and destined for C++23 so far. Yesterday GCC added the command line flag for C++23 but the only feature actually implemented so far is the contains method of std::string. I try to update this repository roughly weekly unless there is some urgency, as was the case with C++20 modules or if there are some important bug fixes.

**Comment by mcc-devel** [comment]
OK, I get that.
